version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/data:/var/lib/mariadb
    healthcheck:
      test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      retries: 3

  nodejs:
    build:
      context: .
      target: builder
    restart: "no"
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # DB_HOST: mariadb
      # DB_USER: user
      # DB_PASSWORD: password
      # DB_DATABASE: ysocialnetwork
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mariadb
    command: ["npm", "run", "dev"]

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
