name: Lighthouse Audit

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - run: echo "${{ env.HOST_URL }}"
      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
            urls: |
                ${{ env.HOST_URL }}
            uploadArtifacts: true
            temporaryPublicStorage: true
